Revert "ci test"
The CI Shows:
Using 1.9.8 as input from file .ruby-version
Error: Unknown version 1.9.8 for ruby on ubuntu-20.04

PERFECT! This proves it's using the specified ruby verison,
when the .ruby-version file is overwritten!

This reverts commit 517fbc1495eb7a8080798e5fa92172c4e841b187.